
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 19 16:46:00 CEST 2015
//----------------------------------------------------

package regExp;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int QUOTED_CHAR = 3;
  public static final int CLOSE_BRACKET = 5;
  public static final int OPEN_BRACE = 16;
  public static final int CARET = 6;
  public static final int ASTERISK = 13;
  public static final int PLUS = 14;
  public static final int ORD_CHAR = 2;
  public static final int DOLLAR = 9;
  public static final int QUESTION_MARK = 15;
  public static final int CLOSE_PARENTHESE = 11;
  public static final int OPEN_BRACKET = 4;
  public static final int COMMA = 18;
  public static final int EOF = 0;
  public static final int CLOSE_BRACE = 17;
  public static final int MINUS = 7;
  public static final int error = 1;
  public static final int DOT = 12;
  public static final int VERTICAL_BAR = 8;
  public static final int OPEN_PARENTHESE = 10;
}

