
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 17 21:26:29 CEST 2015
//----------------------------------------------------

package regExp;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int QUOTED_CHAR = 13;
  public static final int CLOSE_BRACKET = 16;
  public static final int OPEN_BRACE = 27;
  public static final int CARET = 17;
  public static final int ASTERISK = 24;
  public static final int Colon_close = 10;
  public static final int PLUS = 25;
  public static final int ORD_CHAR = 12;
  public static final int DOLLAR = 20;
  public static final int META_CHAR = 4;
  public static final int Open_equal = 5;
  public static final int QUESTION_MARK = 26;
  public static final int Open_colon = 9;
  public static final int CLOSE_PARENTHESE = 22;
  public static final int OPEN_BRACKET = 15;
  public static final int DUP_COUNT = 14;
  public static final int COLL_ELEM_SINGLE = 2;
  public static final int COMMA = 29;
  public static final int EOF = 0;
  public static final int CLOSE_BRACE = 28;
  public static final int MINUS = 18;
  public static final int DOT = 23;
  public static final int error = 1;
  public static final int class_name = 11;
  public static final int Equal_close = 6;
  public static final int VERTICAL_BAR = 19;
  public static final int COLL_ELEM_MULTI = 3;
  public static final int Open_dot = 7;
  public static final int Dot_close = 8;
  public static final int OPEN_PARENTHESE = 21;
}

